name: happy_new_year
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^2.1.0
  animate_do: ^3.0.2

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/json/
  uses-material-design: true

